# Generated by Django 3.2.9 on 2021-11-17 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.SmallIntegerField(choices=[(1, 'Charge'), (2, 'Purchase'), (3, 'Transfer Received'), (4, 'Transfer Sent')], default=1),
        ),
        migrations.AlterField(
            model_name='transactionarchive',
            name='transaction_type',
            field=models.SmallIntegerField(choices=[(1, 'Charge'), (2, 'Purchase'), (3, 'Transfer Received'), (4, 'Transfer Sent')], default=1),
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('receiver_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='transaction.transaction')),
                ('sender_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_transfers', to='transaction.transaction')),
            ],
        ),
    ]
