# Generated by Django 3.2.9 on 2021-11-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20211117_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscore',
            options={'permissions': (('has_score_permission', 'Has score permission'),)},
        ),
    ]
